timezone: Europe/Dublin
locale: "en-IE"
title: A very non-interesting site
name: Daniel Karmark
description: Dan's Github pages
url: https://nolltre.se
repository: "nolltre/nolltre.github.io"

twitter_username: nolltre_se
github_username:  nolltre

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
atom_feed:
  hide: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
